# Write your MySQL query statement below
SELECT DISTINCT L1.NUM AS CONSECUTIVENUMS FROM LOGS L1
INNER JOIN LOGS L2 ON 
L2.ID - 1 = L1.ID INNER JOIN 
LOGS L3 ON L3.ID - 2 = L1.ID
WHERE L1.NUM = L2.NUM AND L2.NUM = L3.NUM
