# Write your MySQL query statement below
SELECT VISITED_ON,
(
    SELECT SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER C1
    WHERE C1.VISITED_ON BETWEEN 
    DATE_SUB(C.VISITED_ON, INTERVAL 6 DAY) AND C.VISITED_ON
) AS AMOUNT,
(
    SELECT ROUND(SUM(AMOUNT)/7,2) FROM CUSTOMER C2 
    WHERE C2.VISITED_ON BETWEEN 
    DATE_SUB(C.VISITED_ON, INTERVAL 6 DAY) AND C.VISITED_ON
) AS AVERAGE_AMOUNT
FROM CUSTOMER C WHERE VISITED_ON >= (SELECT DATE_ADD(MIN(VISITED_ON), 
INTERVAL 6 DAY) FROM CUSTOMER) GROUP BY C.VISITED_ON

