# Write your MySQL query statement below
-- SELECT CUSTOMER_ID,
--  COUNT(CUSTOMER_ID) AS COUNT_NO_TRANS
--  FROM VISITS V
-- LEFT JOIN TRANSACTIONS T ON
-- V.VISIT_ID = T.VISIT_ID WHERE 
-- T.VISIT_ID IS NULL GROUP BY
-- CUSTOMER_ID
SELECT CUSTOMER_ID,
 COUNT(CUSTOMER_ID) AS COUNT_NO_TRANS
 FROM VISITS V
WHERE 
VISIT_ID NOT IN (SELECT DISTINCT VISIT_ID FROM TRANSACTIONS) 
GROUP BY CUSTOMER_ID