# Write your MySQL query statement below
SELECT EMPLOYEE_ID FROM EMPLOYEES E 
WHERE SALARY<30000 AND E.MANAGER_ID IS NOT NULL 
AND E.MANAGER_ID NOT IN (SELECT EMPLOYEE_ID FROM EMPLOYEES)
ORDER BY EMPLOYEE_ID
