# Write your MySQL query statement below
SELECT E.STUDENT_ID, E.STUDENT_NAME, S.SUBJECT_NAME,
COUNT(EX.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS E CROSS JOIN SUBJECTS S 
LEFT JOIN 
EXAMINATIONS EX ON E.STUDENT_ID = EX.STUDENT_ID AND 
S.SUBJECT_NAME = EX.SUBJECT_NAME 
GROUP BY E.STUDENT_ID, S.SUBJECT_NAME 
ORDER BY E.STUDENT_ID, S.SUBJECT_NAME 