# Write your MySQL query statement below
WITH CTE AS (
    SELECT *, ROW_NUMBER() OVER 
    (PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS RN
    FROM ACTIVITY
)
SELECT ROUND(COUNT(PLAYER_ID)/
(SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY),2)
AS FRACTION
FROM ACTIVITY WHERE (PLAYER_ID, EVENT_DATE) IN (
    SELECT PLAYER_ID, DATE_ADD(EVENT_DATE, INTERVAL 1 DAY)
    FROM CTE WHERE RN = 1
)