# Write your MySQL query statement below
SELECT 
LEFT(TRANS_DATE, 7) AS MONTH,
COUNTRY, 
COUNT(STATE) AS TRANS_COUNT,
SUM(STATE='APPROVED') AS APPROVED_COUNT,
SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
SUM((STATE='APPROVED') * AMOUNT) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS GROUP BY MONTH, COUNTRY
