# Write your MySQL query statement below
(WITH TAB AS (
    SELECT * FROM PRODUCTS WHERE CHANGE_DATE<='2019-08-16'
)
SELECT PRODUCT_ID, NEW_PRICE AS PRICE FROM TAB
WHERE (PRODUCT_ID, CHANGE_DATE) IN
(
    SELECT PRODUCT_ID, MAX(CHANGE_DATE) FROM TAB GROUP BY PRODUCT_ID
)
UNION ALL
(SELECT DISTINCT PRODUCT_ID, 10 AS PRICE FROM PRODUCTS WHERE PRODUCT_ID NOT IN (
    SELECT PRODUCT_ID FROM TAB
)))