# Write your MySQL query statement below
WITH CTE AS(
    SELECT *,
    ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS RN
    FROM DELIVERY D    
)
SELECT ROUND(AVG(ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE) * 100, 2)
AS IMMEDIATE_PERCENTAGE
FROM CTE WHERE RN = 1