# Write your MySQL query statement below
WITH S AS (
    SELECT *, IF(RATING<3, 100, 0) AS POOR_RATING FROM QUERIES
)
SELECT QUERY_NAME, ROUND(AVG(RATING/POSITION), 2) AS QUALITY,
ROUND(AVG(POOR_RATING), 2) AS POOR_QUERY_PERCENTAGE
FROM S GROUP BY QUERY_NAME