# Write your MySQL query statement below
SELECT PRODUCT_NAME, SUM(UNIT) AS UNIT
FROM PRODUCTS P INNER JOIN 
ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE ORDER_DATE BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY O.PRODUCT_ID HAVING UNIT>=100