# Write your MySQL query statement below
-- (SELECT USER_ID,
-- (SUM(ACTION = 'CONFIRMED') / COUNT(ACTION)) AS CONFIRMATION_RATE 
-- FROM CONFIRMATIONS C
-- GROUP BY USER_ID)

-- UNION ALL

-- (SELECT USER_ID, 0 AS CONFIRMATION_RATE 
-- FROM SIGNUPS WHERE USER_ID NOT IN (
--     SELECT USER_ID FROM CONFIRMATIONS
-- ))

SELECT s.USER_ID,
       ROUND(
           COALESCE(AVG(c.ACTION = 'CONFIRMED'), 0),
           2
       ) AS CONFIRMATION_RATE
FROM SIGNUPS s
LEFT JOIN CONFIRMATIONS c
    ON s.USER_ID = c.USER_ID
GROUP BY s.USER_ID;