# Write your MySQL query statement below
SELECT E.REPORTS_TO EMPLOYEE_ID , 
(SELECT NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = E.REPORTS_TO) AS NAME,
COUNT(REPORTS_tO) AS REPORTS_COUNT,
ROUND(AVG(AGE)) AS AVERAGE_AGE
FROM EMPLOYEES E
WHERE REPORTS_TO IS NOT NULL
GROUP BY REPORTS_TO ORDER BY EMPLOYEE_ID