# Write your MySQL query statement below
-- SELECT SALARY AS SECONDHIGHESTSALARY FROM EMPLOYEE GROUP BY SALARY 
-- ORDER BY SALARY DESC LIMIT 1, 1

SELECT MAX(SALARY) AS SECONDHIGHESTSALARY FROM EMPLOYEE
WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEE)