# Write your MySQL query statement below
WITH CTE AS (
    SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, SALARY, 
    DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RN
    FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON 
    E.DEPARTMENTID = D.ID  
)
SELECT DEPARTMENT, EMPLOYEE, SALARY FROM CTE 
WHERE RN<=3
