-- # Write your MySQL query statement below
(SELECT NAME AS RESULTS FROM USERS U
JOIN MOVIERATING MR ON U.USER_ID = MR.USER_ID
GROUP BY MR.USER_ID ORDER BY COUNT(MR.USER_ID) DESC,
NAME LIMIT 1)

UNION ALL

(SELECT TITLE FROM MOVIES M
JOIN MOVIERATING MR ON 
M.MOVIE_ID = MR.MOVIE_ID WHERE CREATED_AT
BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY MR.MOVIE_ID ORDER BY 
AVG(RATING) DESC, TITLE LIMIT 1)



