# Write your MySQL query statement below
WITH C AS (
    SELECT COUNT(USER_ID) AS TOTAL FROM USERS
)
SELECT CONTEST_ID,
ROUND((COUNT(USER_ID)/(SELECT TOTAL FROM C)*100), 2) AS PERCENTAGE
FROM REGISTER GROUP BY CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID