# Write your MySQL query statement below
WITH TAB AS (
    (SELECT REQUESTER_ID AS ID FROM REQUESTACCEPTED R1)
    UNION ALL
    (SELECT ACCEPTER_ID AS ID FROM REQUESTACCEPTED)
)
SELECT ID, COUNT(ID) AS NUM FROM TAB GROUP BY ID ORDER BY COUNT(ID) DESC LIMIT 1